[package]
name = "mindown"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slint = "1.8.0"
serde = "=1.0.219"
toml = "0.8.22"

[build-dependencies]
slint-build = "1.8.0"
